version: 2
updates:
  # GitHub Actions Dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"

  # Node.js/npm Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 10
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
      - "automated"
    # Group updates for better management
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "*-dev"
          - "*-test"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        patterns:
          - "@types/*"
          - "*-dev"
          - "*-test"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "vitest*"
          - "cypress*"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific packages if needed
    ignore:
      - dependency-name: "lodash"
        versions: ["4.x"]
      # Example: ignore major version updates for specific packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]

  # Python/pip Dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 8
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Docker Dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 3
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"

  # Terraform Dependencies (if you use IaC)
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 3
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(terraform)"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"
      - "infrastructure"
      - "automated"

  # Composer Dependencies (PHP)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "php"
      - "composer"
      - "automated"

  # Maven Dependencies (Java)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "java"
      - "maven"
      - "automated"

  # Gradle Dependencies (Java/Android)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
      - "automated"

  # Go Modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "automated"

  # Bundler Dependencies (Ruby)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
      - "bundler"
      - "automated"

  # Cargo Dependencies (Rust)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
      - "cargo"
      - "automated"

  # NuGet Dependencies (.NET)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "10:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    reviewers:
      - "lovnishverma"
    assignees:
      - "lovnishverma"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "dotnet"
      - "nuget"
      - "automated"
